### ISSUE TITLE
Commande de type select

### ISSUE THREAD

**Issue by Rockman18** [lunarok/jeedom_xiaomihome#6]
Salut lunarok,

Concernant le menu déroulant des sons prédéfinis, la commande de type select est apparu dans quel version de jeedom. Je suis sur la version stable 2.4.6 est lorsque que j'essaye le dernier code du plugin, la commande des sons prédéfinis se retrouve sans type car select n'existe pas. Serait-ce une fonctionnalité présente uniquement dans la beta de jeedom ?

**Comment by Rockman18** [comment]
lunarok,
je veux bien que tu fermes l'issue mais ça serait sympa de donner une réponse, car je viens de retester et le problème est vraiment là. D'accord ce n'est pas encore déployé à tout le monde mais c'est juste pour éviter le bug le jour de la publication du firmware.

Je viens de supprimer la commande "Son prédéfini" pour qu'elle soit automatiquement recréée.
Dès ce moment là j'obtiens le résultat suivant.
![gateway_commandes](https://cloud.githubusercontent.com/assets/1739183/23615024/59ce2fb0-0285-11e7-8f97-48d5c8c81d73.png)

Et si j'essaye de modifier la gateway et cliquer sur "Sauvegarder" j'obtiens :
![gateway_save](https://cloud.githubusercontent.com/assets/1739183/23615025/59cf5eda-0285-11e7-863a-c2e4659c5d57.png)

`[Maison][Gateway v2][Son prédéfini] Le sous-type de la commande ne peut pas être vide :xiaomihomeCmd Object ( [id:protected] => 570 [logicalId:protected] => mid-list [eqType:protected] => xiaomihome [name:protected] => Son prédéfini [order:protected] => 1 [type:protected] => action [subType:protected] => [eqLogic_id:protected] => 63 [isHistorized:protected] => 0 [unite:protected] => [configuration:protected] => {"switch":"mid","listValue":"0|Sirène 1;1|Sirène 2;2|Accident;3|Compte à rebours;4|Fantôme;5|Sniper;6|Guerre;7|Frappe aérienne;8|Aboiements;10|Sonnette;11|Frappe;12|Hilarious;13|Sonnerie|;20|MiMix;21|Enthousiastic;22|GuitarClassic;23|IceWorldPiano;24|LeisureTime;25|Childhood;26|MorningStreamlet;27|MusicBox;28|Orange;29|Thinker","minValue":"","maxValue":""} [template:protected] => [display:protected] => {"generic_type":"DONT","icon":""} [html:protected] => [_collectDate:protected] => [_valueDate:protected] => [value:protected] => [isVisible:protected] => 1 [_eqLogic:protected] => xiaomihome Object ( [id:protected] => 63 [name:protected] => Gateway v2 [logicalId:protected] => 192.168.1.12 [object_id:protected] => 2 [eqType_name:protected] => xiaomihome [eqReal_id:protected] => [isVisible:protected] => 1 [isEnable:protected] => 1 [configuration:protected] => {"sid":"f0b429b3e2b9","short_id":"0","gateway":"192.168.1.12","model":"gateway","type":"aquara","lastCommunication":"2017-03-06 15:51:31","createtime":"2017-03-03 10:29:29","updatetime":"2017-03-06 15:53:19","token":"*************","password":"********************"} [specificCapatibilities:protected] => [timeout:protected] => [category:protected] => {"heating":"0","security":"0","energy":"0","light":"0","automatism":"0","multimedia":"0","default":"0"} [display:protected] => {"showObjectNameOnview":1,"showObjectNameOndview":1,"showObjectNameOnmview":1} [order:protected] => 0 [_debug:protected] => [_object:protected] => object Object ( [id:object:private] => 2 [name:object:private] => Maison [father_id:object:private] => 1 [isVisible:object:private] => 1 [position:object:private] => 2 [configuration:object:private] => {"parentNumber":1,"summary::global::security":"0","summary::global::motion":"0","summary::global::door":"0","summary::global::windows":"0","summary::global::shutter":"0","summary::global::light":"0","summary::global::outlet":"0","summary::global::temperature":"0","summary::global::humidity":"0","summary::global::luminosity":"0","summary::global::power":"0","summary::hide::desktop::security":"0","summary::hide::desktop::motion":"0","summary::hide::desktop::door":"0","summary::hide::desktop::windows":"0","summary::hide::desktop::shutter":"0","summary::hide::desktop::light":"0","summary::hide::desktop::outlet":"0","summary::hide::desktop::temperature":"0","summary::hide::desktop::humidity":"0","summary::hide::desktop::luminosity":"0","summary::hide::desktop::power":"0","summary::hide::mobile::security":"0","summary::hide::mobile::motion":"0","summary::hide::mobile::door":"0","summary::hide::mobile::windows":"0","summary::hide::mobile::shutter":"0","summary::hide::mobile::light":"0","summary::hide::mobile::outlet":"0","summary::hide::mobile::temperature":"0","summary::hide::mobile::humidity":"0","summary::hide::mobile::luminosity":"0","summary::hide::mobile::power":"0","summary":{"security":[],"motion":[],"door":[],"windows":[],"shutter":[],"light":[],"outlet":[],"temperature":[],"humidity":[],"luminosity":[],"power":[]}} [display:object:private] => {"icon":"<\/i>","tagColor":"#ffffff","tagTextColor":"#000000"} ) [_needRefreshWidget:protected] => [_cmds:protected] => Array ( ) [_templateArray] => Array ( ) ) [_needRefreshWidget:protected] => 1 [_templateArray] => Array ( ) ) `

**Comment by lunarok** [comment]
github c'est pas le support

**Comment by Rockman18** [comment]
OK je comprends, je vais en parler sur le forum alors, je trouve juste dommage de devoir en parler face aux gens qui n'ont pas encore accès à ces évolutions. Les gens ne vont pas comprendre le problème et vont se poser des questions. Mais c'est toi qui voit.
